name: seascape
version: 0.1.0.0
synopsis: An improved interface for UCSD CAPE data
category: Web
author: David Cao
maintainer: david@cao.st
license: MIT
license-file: LICENSE
build-type: Simple
extra-source-files:
  - CHANGELOG.md

dependencies:
  - base >= 4 && < 5

ghc-options:
  - -Wall

library:
  source-dirs:
    src
  dependencies:
    - aeson
    - containers
    - foldl
    - Frames
    - lucid
    - microlens
    - mtl
    - Spock >= 0.13.0.0
    - Spock-lucid
    - monad-logger
    - pipes
    - pipes-safe
    - text
    - vinyl
    - wai-middleware-static
    - wai-extra

benchmarks:
  seascape-bench:
    source-dirs: bench
    main: Main.hs
    dependencies:
      - seascape
      - criterion

executables:
  seascape-app:
    source-dirs: app/server
    main: Main.hs
    dependencies:
      - seascape
      - Spock >= 0.13.0.0

  scrape-sparse:
    source-dirs: app/scrape-sparse
    main: Main.hs
    ghc-options:
      - -O2
      - -fprof-auto
      - -fprof-cafs
    dependencies:
      - aeson
      - bytestring
      - cassava
      - fast-tagsoup
      - http-client
      - http-types
      - scalpel
      - streamly
      - streamly-cassava
      - text
      - webdriver
    
